version: '3.8'

services:
  web:
    build: ./apiproject

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./apiproject:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:14.0-alpine

    volumes:
      - postgres_volume:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api_db

volumes:
  postgres_volume: